### ISSUE TITLE
[BUG] Unable to parse inspec reports with waivers

### ISSUE THREAD

**Issue by spencer-cdw** [mitre/heimdall2#3709]
heimdall is unable to parse inspec reports that were generated using waivers

Waiver file
```
cis-dil-benchmark-2.2.1.3:
  expiration_date: '2022-12-31'
  justification: https://github.com/dev-sec/cis-dil-benchmark/issues/129
  run: 'true'
```

![Screen Shot 2022-11-02 at 12 23 27 PM](https://user-images.githubusercontent.com/109251274/199571566-8f736ca9-8ee3-49c8-b2fd-dea8665571ac.png)

```
            "attributes": [
                {
                    "name": "packer_build_name",
                    "options": {
                        "value": "ubuntu-bionic"
                    }
                },
                {
                    "name": "packer_builder_type",
                    "options": {
                        "value": "googlecompute"
                    }
                },
                {
                    "name": "cis-dil-benchmark-2.2.1.3",
                    "options": {
                        "value": {
                            "expiration_date": "2022-12-31",
                            "justification": "https://github.com/dev-sec/cis-dil-benchmark/issues/129",
                            "run": "true"
                        }
                    }
                },
                ```
[inspec_09889747-e780-233f-ef7b-e6be2dfced56.json.zip](https://github.com/mitre/heimdall2/files/9923158/inspec_09889747-e780-233f-ef7b-e6be2dfced56.json.zip)

## Theories

The waiver file has a string for `expiration_date` and `run` whereas I suspect that heimdall is expecting a boolean or integer

String

```
cis-dil-benchmark-2.2.1.3:
  expiration_date: '2022-12-31'
  justification: https://github.com/dev-sec/cis-dil-benchmark/issues/129
  run: 'true'
```
Bool/Integer
```
cis-dil-benchmark-2.2.1.3:
  expiration_date: 2022-12-31
  justification: https://github.com/dev-sec/cis-dil-benchmark/issues/129
  run: true
```
https://docs.chef.io/inspec/waivers/
